=== cadaeibf/Lintupaivakirja1.0/Lintupaivakirja1.0/src/kirjasto/havaintolista.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="lista">
	<xs:element name="laji" minOccurs="0" maxOccurs="unbounded">
	<xs:complexType>
		<xs:sequence>	
			<xs:element name="nimi" type="xs:string"/>
			<xs:element name="havainto" maxOccurs="unbounded">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="paikka" type="xs:string"/>
					<xs:element name="pvm" type="xs:date"/>
					<xs:element name="lkm">
						<xs:simpleType>
							<xs:restriction base="xs:integer">
								<xs:minInclusive value="1"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
					<xs:any minOccurs="0"/>
				</xs:sequence>
			</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	</xs:element>
</xs:element>

</xs:schema>

=== cadaeibf/Lintupaivakirja1.0/xml/testi.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><lista xmlns:xs="http://www.w3.org/2001/XMLSchema" xs:schemaLocation="havaintolista.xsd"><laji><nimi>käpytikka</nimi><havainnot><havainto><paikka>lappeenranta, skinnarila</paikka><pvm>2014-03-02</pvm><lkm>1</lkm></havainto><havainto><paikka>paloheinä</paikka><pvm>2014-03-30</pvm><lkm>1</lkm></havainto></havainnot></laji><laji><nimi>lapinpöllö</nimi><havainnot><havainto><paikka>helsinki, laajasalo</paikka><pvm>2013-04-29</pvm><lkm>1</lkm></havainto><havainto><paikka>helsinki, kannelmäki</paikka><pvm>2013-04-30</pvm><lkm>1</lkm></havainto></havainnot></laji><laji><nimi>merikotka</nimi><havainnot><havainto><paikka>brändö</paikka><pvm>2014-04-12</pvm><lkm>1</lkm></havainto></havainnot></laji><laji><nimi>niittysuohaukka</nimi><havainnot><havainto><paikka>espoo, matalajärvi</paikka><pvm>2013-06-30</pvm><lkm>1</lkm></havainto></havainnot></laji><laji><nimi>ruskosuohaukka</nimi><havainnot><havainto><paikka>rauman maalaiskunta</paikka><pvm>2013-06-20</pvm><lkm>1</lkm></havainto></havainnot></laji><laji><nimi>sinisorsa</nimi><havainnot><havainto><paikka>tokoinranta</paikka><pvm>2013-04-30</pvm><lkm>15</lkm></havainto><havainto><paikka>tokoinranta</paikka><pvm>2014-04-30</pvm><lkm>5</lkm></havainto></havainnot></laji><laji><nimi>talitiainen</nimi><havainnot><havainto><paikka>tuupovaara</paikka><pvm>2012-06-12</pvm><lkm>1</lkm></havainto><havainto><paikka>helsinki, kaisaniemi</paikka><pvm>2013-07-12</pvm><lkm>1</lkm></havainto></havainnot></laji><laji><nimi>varis</nimi><havainnot><havainto><paikka>helsinki, malmi</paikka><pvm>2014-04-12</pvm><lkm>4</lkm></havainto></havainnot></laji><laji><nimi>västäräkki</nimi><havainnot><havainto><paikka>sipoo, landbo</paikka><pvm>2014-03-10</pvm><lkm>2</lkm></havainto></havainnot></laji></lista>

=== cadaeibf/Lintupaivakirja1.0/xml/havaintolista.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><lista xmlns:xs="http://www.w3.org/2001/XMLSchema" xs:noNamespaceSchemaLocation="havaintolista.xsd"><laji>hippiäinen<havainnot><havainto><paikka>sipoo</paikka><pvm>2014-04-24</pvm><lkm>1</lkm></havainto></havainnot></laji><laji>merikotka<havainnot><havainto><paikka>brändö</paikka><pvm>2014-04-29</pvm><lkm>1</lkm></havainto></havainnot></laji><laji>sinisorsa<havainnot><havainto><paikka>tokoinranta</paikka><pvm>2014-04-29</pvm><lkm>4</lkm></havainto></havainnot></laji></lista>

=== cadaeibf/Lintupaivakirja1.0/Lintupaivakirja1.0/havainnot/havainnot.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><lista xmlns:xs="http://www.w3.org/2001/XMLSchema" xs:schemaLocation="havaintolista.xsd"><laji><nimi>käpytikka</nimi><havainnot><havainto><paikka>helsinki</paikka><pvm>2014-05-15</pvm><lkm>1</lkm></havainto></havainnot></laji><laji><nimi>lapinpöllö</nimi><havainnot><havainto><paikka>kannelmäki</paikka><pvm>2013-05-15</pvm><lkm>1</lkm></havainto></havainnot></laji><laji><nimi>merikotka</nimi><havainnot><havainto><paikka>brändö</paikka><pvm>2014-04-12</pvm><lkm>1</lkm></havainto></havainnot></laji><laji><nimi>niittysuohaukka</nimi><havainnot><havainto><paikka>sipoo</paikka><pvm>2013-08-15</pvm><lkm>1</lkm></havainto></havainnot></laji><laji><nimi>ruskosuohaukka</nimi><havainnot><havainto><paikka>rauma</paikka><pvm>2013-06-15</pvm><lkm>1</lkm></havainto></havainnot></laji><laji><nimi>sinisorsa</nimi><havainnot><havainto><paikka>helsinki</paikka><pvm>2012-02-15</pvm><lkm>14</lkm></havainto></havainnot></laji><laji><nimi>talitiainen</nimi><havainnot><havainto><paikka>helsinki</paikka><pvm>2013-04-12</pvm><lkm>1</lkm></havainto></havainnot></laji><laji><nimi>varis</nimi><havainnot><havainto><paikka>helsinki</paikka><pvm>2014-05-15</pvm><lkm>3</lkm></havainto></havainnot></laji><laji><nimi>västäräkki</nimi><havainnot><havainto><paikka>helsinki</paikka><pvm>2014-05-15</pvm><lkm>1</lkm></havainto></havainnot></laji></lista>
